# Generated by Django 2.2.19 on 2023-01-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hourtime',
            field=models.ForeignKey(blank=True, help_text='Выберите время собеседования', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SobesTime', verbose_name='Время собеседования'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='baza',
            field=models.TextField(blank=True, help_text='Вставьте ссылку на анкету', null=True, verbose_name='Ссылка на анкету'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='name',
            field=models.CharField(blank=True, help_text='Введите ФИО', max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='number',
            field=models.IntegerField(blank=True, help_text='Введите номер телефона', null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='town',
            field=models.CharField(blank=True, help_text='Введите город', max_length=100, null=True, verbose_name='Город'),
        ),
    ]
