# Generated by Django 2.2.9 on 2023-01-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230108_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SobesTime',
            new_name='InterviewTime',
        ),
    ]
