# Generated by Django 2.2.9 on 2023-01-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230109_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prioritet',
            new_name='Priority',
        ),
    ]
