# Generated by Django 2.2.19 on 2023-01-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230109_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='number',
            field=models.TextField(blank=True, help_text='Введите номер телефона', null=True, verbose_name='Номер телефона'),
        ),
    ]
