# Generated by Django 3.2.16 on 2023-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230222_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.CharField(default=1, help_text='Вставьте номер кандидата', max_length=20, verbose_name='Номер кандидата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Введите текст сообщения', max_length=300, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='sampleresponse',
            name='text',
            field=models.TextField(default=1, help_text='Введите текст сообщения', max_length=300, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samplestraight',
            name='text',
            field=models.TextField(default=1, help_text='Введите текст сообщения', max_length=300, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
    ]
