# Generated by Django 2.2.19 on 2023-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230111_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='number',
            field=models.CharField(blank=True, help_text='Введите номер телефона', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
