# Generated by Django 2.2.19 on 2023-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230111_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='number',
            field=models.CharField(blank=True, help_text='Вставьте номер кандидата', max_length=20, null=True, verbose_name='Номер кандидата'),
        ),
    ]
