# Generated by Django 2.2.19 on 2023-01-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Шаблон отклика',
                'verbose_name_plural': 'Шаблоны отклика',
            },
        ),
    ]
