# Generated by Django 3.2.16 on 2023-03-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230310_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='cities',
            new_name='city',
        ),
    ]
