# Generated by Django 2.2.19 on 2023-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sampleresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStraight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Шаблон прямого поиска',
                'verbose_name_plural': 'Шаблоны прямых поисков',
            },
        ),
    ]
