# Generated by Django 3.2.16 on 2023-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_cities_message_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст сообщения', max_length=300, verbose_name='Текст сообщения')),
                ('number', models.CharField(help_text='Вставьте номер кандидата', max_length=20, verbose_name='Номер кандидата')),
                ('header', models.TextField(blank=True, max_length=500, null=True, verbose_name='Пример шапки запроса')),
                ('city', models.TextField(max_length=500, verbose_name='Площадка')),
                ('town', models.CharField(blank=True, help_text='Введите город', max_length=100, null=True, verbose_name='Город')),
                ('name', models.CharField(blank=True, help_text='Введите ФИО', max_length=100, null=True, verbose_name='ФИО')),
                ('base', models.TextField(blank=True, help_text='Вставьте ссылку на анкету', null=True, verbose_name='Ссылка на анкету')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.DeleteModel(
            name='Zapros',
        ),
    ]
