# Generated by Django 2.2.19 on 2023-01-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_samplestraight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplestraight',
            name='price',
        ),
    ]
