# Generated by Django 2.2.19 on 2023-01-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_samplestraight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleresponse',
            name='number',
            field=models.CharField(help_text='Вставьте номер кандидата', max_length=20, verbose_name='Номер кандидата'),
        ),
        migrations.AlterField(
            model_name='samplestraight',
            name='name',
            field=models.CharField(blank=True, help_text='Введите своё имя', max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='samplestraight',
            name='number',
            field=models.CharField(help_text='Вставьте номер кандидата', max_length=20, verbose_name='Номер кандидата'),
        ),
    ]
