# Generated by Django 2.2.19 on 2023-01-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230112_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTimeOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Время собеседования',
                'verbose_name_plural': 'Время собеседований',
            },
        ),
        migrations.AlterModelOptions(
            name='interviewtime',
            options={},
        ),
        migrations.CreateModel(
            name='MessageOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('weektime', models.DateField(blank=True, help_text='Выберите дату собеседования', null=True, verbose_name='Дата собеседования')),
                ('text', models.TextField(help_text='Введите текст сообщения', verbose_name='Текст сообщения')),
                ('number', models.CharField(blank=True, help_text='Вставьте номер кандидата', max_length=20, null=True, verbose_name='Номер кандидата')),
                ('cities', models.ForeignKey(blank=True, help_text='Выберите город', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.City', verbose_name='Город')),
                ('hourtime', models.ForeignKey(blank=True, help_text='Выберите время собеседования', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.InterviewTimeOffice', verbose_name='Время собеседования')),
            ],
            options={
                'verbose_name': 'Сообщение_Офия',
                'verbose_name_plural': 'Сообщения_Офис',
            },
        ),
    ]
