# Generated by Django 2.2.19 on 2023-01-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230112_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewtime',
            options={'verbose_name': 'Время собеседования', 'verbose_name_plural': 'Время собеседований'},
        ),
        migrations.AlterModelOptions(
            name='interviewtimeoffice',
            options={'verbose_name': 'Время собеседования в офисе', 'verbose_name_plural': 'Время собеседований в офисе'},
        ),
        migrations.AlterModelOptions(
            name='messageoffice',
            options={'verbose_name': 'Сообщение_Офис', 'verbose_name_plural': 'Сообщения_Офис'},
        ),
    ]
