# Generated by Django 2.2.19 on 2023-01-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230112_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewtime',
            options={'ordering': ['value'], 'verbose_name': 'Время собеседования', 'verbose_name_plural': 'Время собеседований'},
        ),
    ]
